/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package control_api

import (
	"encoding/json"
)

// checks if the ModelsLogoutResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsLogoutResponse{}

// ModelsLogoutResponse struct for ModelsLogoutResponse
type ModelsLogoutResponse struct {
	LogoutUrl *string `json:"logout_url,omitempty"`
}

// NewModelsLogoutResponse instantiates a new ModelsLogoutResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsLogoutResponse() *ModelsLogoutResponse {
	this := ModelsLogoutResponse{}
	return &this
}

// NewModelsLogoutResponseWithDefaults instantiates a new ModelsLogoutResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsLogoutResponseWithDefaults() *ModelsLogoutResponse {
	this := ModelsLogoutResponse{}
	return &this
}

// GetLogoutUrl returns the LogoutUrl field value if set, zero value otherwise.
func (o *ModelsLogoutResponse) GetLogoutUrl() string {
	if o == nil || IsNil(o.LogoutUrl) {
		var ret string
		return ret
	}
	return *o.LogoutUrl
}

// GetLogoutUrlOk returns a tuple with the LogoutUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLogoutResponse) GetLogoutUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LogoutUrl) {
		return nil, false
	}
	return o.LogoutUrl, true
}

// HasLogoutUrl returns a boolean if a field has been set.
func (o *ModelsLogoutResponse) HasLogoutUrl() bool {
	if o != nil && !IsNil(o.LogoutUrl) {
		return true
	}

	return false
}

// SetLogoutUrl gets a reference to the given string and assigns it to the LogoutUrl field.
func (o *ModelsLogoutResponse) SetLogoutUrl(v string) {
	o.LogoutUrl = &v
}

func (o ModelsLogoutResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsLogoutResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LogoutUrl) {
		toSerialize["logout_url"] = o.LogoutUrl
	}
	return toSerialize, nil
}

type NullableModelsLogoutResponse struct {
	value *ModelsLogoutResponse
	isSet bool
}

func (v NullableModelsLogoutResponse) Get() *ModelsLogoutResponse {
	return v.value
}

func (v *NullableModelsLogoutResponse) Set(val *ModelsLogoutResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsLogoutResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsLogoutResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsLogoutResponse(val *ModelsLogoutResponse) *NullableModelsLogoutResponse {
	return &NullableModelsLogoutResponse{value: val, isSet: true}
}

func (v NullableModelsLogoutResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsLogoutResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
