/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package control_api

import (
	"encoding/json"
)

// checks if the ModelsLoginStartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsLoginStartResponse{}

// ModelsLoginStartResponse struct for ModelsLoginStartResponse
type ModelsLoginStartResponse struct {
	AuthorizationRequestUrl *string `json:"authorization_request_url,omitempty"`
}

// NewModelsLoginStartResponse instantiates a new ModelsLoginStartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsLoginStartResponse() *ModelsLoginStartResponse {
	this := ModelsLoginStartResponse{}
	return &this
}

// NewModelsLoginStartResponseWithDefaults instantiates a new ModelsLoginStartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsLoginStartResponseWithDefaults() *ModelsLoginStartResponse {
	this := ModelsLoginStartResponse{}
	return &this
}

// GetAuthorizationRequestUrl returns the AuthorizationRequestUrl field value if set, zero value otherwise.
func (o *ModelsLoginStartResponse) GetAuthorizationRequestUrl() string {
	if o == nil || IsNil(o.AuthorizationRequestUrl) {
		var ret string
		return ret
	}
	return *o.AuthorizationRequestUrl
}

// GetAuthorizationRequestUrlOk returns a tuple with the AuthorizationRequestUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLoginStartResponse) GetAuthorizationRequestUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizationRequestUrl) {
		return nil, false
	}
	return o.AuthorizationRequestUrl, true
}

// HasAuthorizationRequestUrl returns a boolean if a field has been set.
func (o *ModelsLoginStartResponse) HasAuthorizationRequestUrl() bool {
	if o != nil && !IsNil(o.AuthorizationRequestUrl) {
		return true
	}

	return false
}

// SetAuthorizationRequestUrl gets a reference to the given string and assigns it to the AuthorizationRequestUrl field.
func (o *ModelsLoginStartResponse) SetAuthorizationRequestUrl(v string) {
	o.AuthorizationRequestUrl = &v
}

func (o ModelsLoginStartResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsLoginStartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthorizationRequestUrl) {
		toSerialize["authorization_request_url"] = o.AuthorizationRequestUrl
	}
	return toSerialize, nil
}

type NullableModelsLoginStartResponse struct {
	value *ModelsLoginStartResponse
	isSet bool
}

func (v NullableModelsLoginStartResponse) Get() *ModelsLoginStartResponse {
	return v.value
}

func (v *NullableModelsLoginStartResponse) Set(val *ModelsLoginStartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsLoginStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsLoginStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsLoginStartResponse(val *ModelsLoginStartResponse) *NullableModelsLoginStartResponse {
	return &NullableModelsLoginStartResponse{value: val, isSet: true}
}

func (v NullableModelsLoginStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsLoginStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
