/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package control_api

import (
	"encoding/json"
)

// checks if the ModelsRefreshTokenRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsRefreshTokenRequest{}

// ModelsRefreshTokenRequest struct for ModelsRefreshTokenRequest
type ModelsRefreshTokenRequest struct {
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// NewModelsRefreshTokenRequest instantiates a new ModelsRefreshTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsRefreshTokenRequest() *ModelsRefreshTokenRequest {
	this := ModelsRefreshTokenRequest{}
	return &this
}

// NewModelsRefreshTokenRequestWithDefaults instantiates a new ModelsRefreshTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsRefreshTokenRequestWithDefaults() *ModelsRefreshTokenRequest {
	this := ModelsRefreshTokenRequest{}
	return &this
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *ModelsRefreshTokenRequest) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRefreshTokenRequest) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *ModelsRefreshTokenRequest) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *ModelsRefreshTokenRequest) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

func (o ModelsRefreshTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsRefreshTokenRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RefreshToken) {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	return toSerialize, nil
}

type NullableModelsRefreshTokenRequest struct {
	value *ModelsRefreshTokenRequest
	isSet bool
}

func (v NullableModelsRefreshTokenRequest) Get() *ModelsRefreshTokenRequest {
	return v.value
}

func (v *NullableModelsRefreshTokenRequest) Set(val *ModelsRefreshTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsRefreshTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsRefreshTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsRefreshTokenRequest(val *ModelsRefreshTokenRequest) *NullableModelsRefreshTokenRequest {
	return &NullableModelsRefreshTokenRequest{value: val, isSet: true}
}

func (v NullableModelsRefreshTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsRefreshTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
