/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package control_api

import (
	"encoding/json"
)

// checks if the ModelsLoginEndResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsLoginEndResponse{}

// ModelsLoginEndResponse struct for ModelsLoginEndResponse
type ModelsLoginEndResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	Handled      *bool   `json:"handled,omitempty"`
	LoggedIn     *bool   `json:"logged_in,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// NewModelsLoginEndResponse instantiates a new ModelsLoginEndResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsLoginEndResponse() *ModelsLoginEndResponse {
	this := ModelsLoginEndResponse{}
	return &this
}

// NewModelsLoginEndResponseWithDefaults instantiates a new ModelsLoginEndResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsLoginEndResponseWithDefaults() *ModelsLoginEndResponse {
	this := ModelsLoginEndResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *ModelsLoginEndResponse) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLoginEndResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *ModelsLoginEndResponse) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *ModelsLoginEndResponse) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetHandled returns the Handled field value if set, zero value otherwise.
func (o *ModelsLoginEndResponse) GetHandled() bool {
	if o == nil || IsNil(o.Handled) {
		var ret bool
		return ret
	}
	return *o.Handled
}

// GetHandledOk returns a tuple with the Handled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLoginEndResponse) GetHandledOk() (*bool, bool) {
	if o == nil || IsNil(o.Handled) {
		return nil, false
	}
	return o.Handled, true
}

// HasHandled returns a boolean if a field has been set.
func (o *ModelsLoginEndResponse) HasHandled() bool {
	if o != nil && !IsNil(o.Handled) {
		return true
	}

	return false
}

// SetHandled gets a reference to the given bool and assigns it to the Handled field.
func (o *ModelsLoginEndResponse) SetHandled(v bool) {
	o.Handled = &v
}

// GetLoggedIn returns the LoggedIn field value if set, zero value otherwise.
func (o *ModelsLoginEndResponse) GetLoggedIn() bool {
	if o == nil || IsNil(o.LoggedIn) {
		var ret bool
		return ret
	}
	return *o.LoggedIn
}

// GetLoggedInOk returns a tuple with the LoggedIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLoginEndResponse) GetLoggedInOk() (*bool, bool) {
	if o == nil || IsNil(o.LoggedIn) {
		return nil, false
	}
	return o.LoggedIn, true
}

// HasLoggedIn returns a boolean if a field has been set.
func (o *ModelsLoginEndResponse) HasLoggedIn() bool {
	if o != nil && !IsNil(o.LoggedIn) {
		return true
	}

	return false
}

// SetLoggedIn gets a reference to the given bool and assigns it to the LoggedIn field.
func (o *ModelsLoginEndResponse) SetLoggedIn(v bool) {
	o.LoggedIn = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *ModelsLoginEndResponse) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsLoginEndResponse) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *ModelsLoginEndResponse) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *ModelsLoginEndResponse) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

func (o ModelsLoginEndResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsLoginEndResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessToken) {
		toSerialize["access_token"] = o.AccessToken
	}
	if !IsNil(o.Handled) {
		toSerialize["handled"] = o.Handled
	}
	if !IsNil(o.LoggedIn) {
		toSerialize["logged_in"] = o.LoggedIn
	}
	if !IsNil(o.RefreshToken) {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	return toSerialize, nil
}

type NullableModelsLoginEndResponse struct {
	value *ModelsLoginEndResponse
	isSet bool
}

func (v NullableModelsLoginEndResponse) Get() *ModelsLoginEndResponse {
	return v.value
}

func (v *NullableModelsLoginEndResponse) Set(val *ModelsLoginEndResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsLoginEndResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsLoginEndResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsLoginEndResponse(val *ModelsLoginEndResponse) *NullableModelsLoginEndResponse {
	return &NullableModelsLoginEndResponse{value: val, isSet: true}
}

func (v NullableModelsLoginEndResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsLoginEndResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
