/*
Nexodus API

This is the Nexodus API Server.

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package control_api

import (
	"encoding/json"
)

// checks if the ModelsRefreshTokenResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsRefreshTokenResponse{}

// ModelsRefreshTokenResponse struct for ModelsRefreshTokenResponse
type ModelsRefreshTokenResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// NewModelsRefreshTokenResponse instantiates a new ModelsRefreshTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsRefreshTokenResponse() *ModelsRefreshTokenResponse {
	this := ModelsRefreshTokenResponse{}
	return &this
}

// NewModelsRefreshTokenResponseWithDefaults instantiates a new ModelsRefreshTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsRefreshTokenResponseWithDefaults() *ModelsRefreshTokenResponse {
	this := ModelsRefreshTokenResponse{}
	return &this
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *ModelsRefreshTokenResponse) GetAccessToken() string {
	if o == nil || IsNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRefreshTokenResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil || IsNil(o.AccessToken) {
		return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *ModelsRefreshTokenResponse) HasAccessToken() bool {
	if o != nil && !IsNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *ModelsRefreshTokenResponse) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetRefreshToken returns the RefreshToken field value if set, zero value otherwise.
func (o *ModelsRefreshTokenResponse) GetRefreshToken() string {
	if o == nil || IsNil(o.RefreshToken) {
		var ret string
		return ret
	}
	return *o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsRefreshTokenResponse) GetRefreshTokenOk() (*string, bool) {
	if o == nil || IsNil(o.RefreshToken) {
		return nil, false
	}
	return o.RefreshToken, true
}

// HasRefreshToken returns a boolean if a field has been set.
func (o *ModelsRefreshTokenResponse) HasRefreshToken() bool {
	if o != nil && !IsNil(o.RefreshToken) {
		return true
	}

	return false
}

// SetRefreshToken gets a reference to the given string and assigns it to the RefreshToken field.
func (o *ModelsRefreshTokenResponse) SetRefreshToken(v string) {
	o.RefreshToken = &v
}

func (o ModelsRefreshTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsRefreshTokenResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessToken) {
		toSerialize["access_token"] = o.AccessToken
	}
	if !IsNil(o.RefreshToken) {
		toSerialize["refresh_token"] = o.RefreshToken
	}
	return toSerialize, nil
}

type NullableModelsRefreshTokenResponse struct {
	value *ModelsRefreshTokenResponse
	isSet bool
}

func (v NullableModelsRefreshTokenResponse) Get() *ModelsRefreshTokenResponse {
	return v.value
}

func (v *NullableModelsRefreshTokenResponse) Set(val *ModelsRefreshTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsRefreshTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsRefreshTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsRefreshTokenResponse(val *ModelsRefreshTokenResponse) *NullableModelsRefreshTokenResponse {
	return &NullableModelsRefreshTokenResponse{value: val, isSet: true}
}

func (v NullableModelsRefreshTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsRefreshTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
